api_version: 1
runtime: python27

handlers:
- url: /
  secure: always
  static_files: www/index.html
  upload: www/index.html
  login: required

- url: /(.*)
  secure: always
  static_files: www/\1
  upload: www/(.*)
  login: required

service: default
threadsafe: true
